# Generated by Django 5.2.7 on 2025-11-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='acessibilidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarto',
            name='aquecedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarto',
            name='ar_condicionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarto',
            name='banheiro_privativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quarto',
            name='beliche',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarto',
            name='cofre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarto',
            name='escritorio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarto',
            name='frigobar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarto',
            name='lavanderia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarto',
            name='microondas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarto',
            name='qtd_cama_casal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarto',
            name='qtd_cama_solteiro',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quarto',
            name='secador_cabelo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarto',
            name='telefone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarto',
            name='tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarto',
            name='varanda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarto',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
